version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:17.0  # Ajusta a la versión de Java que necesites
    steps:
      - checkout
      - run: mvn clean install # Compila y ejecuta los tests
      - run: mvn jacoco:report # Genera el informe de cobertura

workflows:
  version: 2
  build:
    jobs:
      - build_and_test