version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn clean install # Compila y ejecuta los tests
      - run: mvn jacoco:report # Genera el informe de cobertura
      - run: mvn checkstyle:check # Ejecuta el linting de la aplicación

workflows:
  version: 2
  build:
    jobs:
      - build_and_test